#!/usr/bin/env zsh

cpbook() {
    if [[ -d book ]]; then
        rm -rf book && echo "✓ rm book/" || echo "rm book/"
    fi

    mkdir book && echo "✓ created book/"
    cp ../*.typ ./book/ && echo "✓ copy typ files"
    cp ../lib ./book/ -r && echo "✓ copy lib/"
}

cpimg() {
    cp ../images ./book/ -r && echo "✓ copied images"
    sd 'version="1.1"' '$0 fill="#aaaaaa"' ./book/images/diagram/*.svg && echo "✓ update svg fill"
    sd 'svg">' '$0\n<rect width="100%" height="100%" fill="#333333" />' ./book/images/diagram/*.svg && echo "✓ update svg background"
}

cpbook && cpimg

cd book && pandoc HypermediaSystems-ebook.typ \
    -o ../HypermediaSystemsBook.epub \
    --toc --split-level=3 --top-level-division=chapter \
    --css lib/epub.css \
    --metadata-file lib/epub.yaml \
    --epub-cover-image=images/cover.png && echo "✓ epub created"

cp ../HypermediaSystemsBook.epub $EPUB_LIB && echo "✓ copied to library"
